Repository GerardoWacker/batnav, pull requests merged in 2022-06, with the labels that each got.

#31 Final push to make pull request
  assets/textures/green_icon.png
  assets/textures/icono.png
  assets/textures/red_icon.png
  src/batnav/ui/boards/Board.java
  src/batnav/ui/screens/LoginScreen.java
  src/batnav/ui/screens/MatchScreen.java
Labels: size/L

#33 Update code
  assets/textures/green_icon.png
  assets/textures/icono.png
  assets/textures/red_icon.png
  src/batnav/config/ConfigManager.java
  src/batnav/instance/Game.java
  src/batnav/online/match/Match.java
  src/batnav/online/match/MatchManager.java
  src/batnav/online/session/SessionManager.java
  src/batnav/online/socket/Connection.java
  src/batnav/ui/boards/Board.java
  src/batnav/ui/components/RotatingImageLabel.java
  src/batnav/ui/screens/LoginScreen.java
  src/batnav/ui/screens/MainMenuScreen.java
  src/batnav/ui/screens/MatchScreen.java
  src/batnav/ui/screens/ShipSelectionScreen.java
  src/batnav/ui/screens/SplashScreen.java
  src/batnav/utils/Sambayon.java
Labels: size/XL

#34 Updated both `LoginScreen` and `RegisterScreen`
  assets/textures/green_icon.png
  assets/textures/red_icon.png
  src/batnav/online/socket/Connection.java
  src/batnav/ui/screens/LoginScreen.java
  src/batnav/ui/screens/MatchScreen.java
  src/batnav/ui/screens/RegisterScreen.java
Labels: size/L

#32 Added SettingsScreen, MainMenuScreen, and mock buttons
  assets/mainmenu/BatallaNaval.jpg
  assets/mainmenu/Casuals.png
  assets/mainmenu/LeftArrow.png
  assets/mainmenu/LetsPlay.png
  assets/mainmenu/PreviasPartidas.png
  assets/mainmenu/Ranked.png
  assets/mainmenu/RightArrow.png
  assets/mainmenu/SettingsEngine.png
  assets/mainmenu/imagesOfUsers/Sth.png
  assets/mainmenu/ranked.png
  src/batnav/ui/screens/SettingsScreen.java
  src/batnav/ui/screens/customizeItYourself.java
  src/batnav/ui/screens/darkMode.java
  src/batnav/ui/screens/lightMode.java
Labels: size/L

#35 Added textures for buttons
  assets/textures/boton_amarillo_degrade.png
  assets/textures/boton_amarillo_degrade_hover.png
  assets/textures/boton_azul_degrade.png
  assets/textures/boton_azul_degrade_hover.png
  assets/textures/copa_oro.png
  assets/textures/icono.png
Labels: size/XS

#36 Update codebase
  assets/textures/boton_amarillo_degrade.png
  assets/textures/boton_amarillo_degrade_hover.png
  assets/textures/boton_azul_degrade.png
  assets/textures/boton_azul_degrade_hover.png
  assets/textures/copa_oro.png
  assets/textures/icono.png
Labels: size/XS

#38 Update code for `implement-design`
  src/batnav/ui/screens/MainMenuScreen.java
Labels: size/L

#40 Working on SettingsScreen
  src/batnav/ui/screens/SettingsScreen.java
Labels: size/S
